### ISSUE TITLE
Can not stop player

### ISSUE THREAD

**Issue by mfranchini** [Tom-Hirschberger/MMM-MplayerRadio#30] opened 2023-11-04 14:47 UTC
Hi
i installed MMM-PlayerRadio and it work, but when i press up or down volume button i receive this error:

[04.11.2023 15:30.08.490] [LOG]   [VOLUME] Set Volume Error: Error: Command failed: amixer sset -M 'PCM' 5%
amixer: Unable to find simple control 'PCM',0

    at ChildProcess.exithandler (node:child_process:430:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:322:12) {
  code: 1,
  killed: false,
  signal: null,
  cmd: "amixer sset -M 'PCM' 5%"
}

i installed also MMM-Volume, but the error persist
Thanks

**Comment by Tom-Hirschberger** [comment] 2023-11-04 16:41
Hi,

as the Radio module only uses MMM-Volume the problem is surely in MMM-Volume.
The commands the volume module needs to call depend highly on your system.
Which one are you using?
Raspberry Buster, Bullseye or Bookworm? 
Do you use any Hat like Hifiberry or the build in chip to output sound?
I am pritty sure the module has not been tested with Bookworm yet and the sound system changed massifly with Bookworm.

**Comment by mfranchini** [comment] 2023-11-04 16:53
Hi
i use Rasperry pi3 model B with o.s. bullseyes legacy, but the error raise also before installed MMM-Volume

Marco Franchini
3487555030

**Comment by Tom-Hirschberger** [comment] 2023-11-04 17:28
Hi,

but my module only sends a notification to the volume module.
Are you sure you use MMM-MplayerRadio or do you use EXT-RadioPlayer?
If you use EXT-RadioPlayer you need to ask for support in the forum of bogus not as I do not know any details of his module.

**Comment by mfranchini** [comment] 2023-11-04 17:39
Yes i use MMM-MplayerRadio.
Thanks now i send a issue to MMM-Volume

Good luck

Marco Franchini
3487555030

**Comment by Tom-Hirschberger** [comment] 2023-11-04 19:14
I use this MMM-Volume config in my Bullseye setup:

```js
		{
			module: "MMM-Volume",
			position: "top_left", // It is meaningless. but you should set.
			config: {
			  usePresetScript: "PULSE",
			}
		},
```

How does your config look like?

**Comment by mfranchini** [comment] 2023-11-04 19:16
Thanks
tomorrow i try your configuration.

Good Night

Marco Franchini
3487555030

**Comment by Tom-Hirschberger** [comment] 2023-11-05 09:19
I will try to investigate the problem further in the evening. But I can not promise I will have time today

**Comment by mfranchini** [comment] 2023-11-05 09:21
No problem, i can wait

Marco Franchini
3487555030

**Comment by mfranchini** [comment] 2023-11-05 09:28
Hi,
with “PULSE”, work thanks

Marco Franchini
3487555030

**Comment by Tom-Hirschberger** [comment] 2023-11-05 09:30
Perfect. Great to hear that.
Have fun with the modules then.
I will close this issue.
If you have any problems with the module feel free to open a new one.

**Comment by mfranchini** [comment] 2023-11-05 09:37
Thanks
but there is another problem, i have only one station and when i press next o previous button start another instance and is not possible to stop this, if i press stop button only one instance stop and the radio continues to play. I must reset raspberry to stop play.

Marco Franchini
3487555030

**Comment by Tom-Hirschberger** [comment] 2023-11-05 09:40
Can you post your Config please?
Do you use mplayer or (as suggested) the vlcWrapper.bash?

**Comment by mfranchini** [comment] 2023-11-05 09:44
{
                        module: "MMM-Volume",
                        position: "bottom_center", // It is meaningless. but you should set.
                        config: {
                                upDownScale: 5,
                                // for VOLUME_UP or VOLUME_DOWN.

                                volumeOnStart: 20,
                                // If you set this, this volume will be applied on start of Magic>
                                volumeText: "Vol: #VOLUME#%",
                                // Showing volume.
                                usePresetScript: "PULSE", // "ALSA" is supported by default.
                                //volumeOnStart: 50


                        }
                },

                {
                        module: "MMM-MplayerRadio",
                        header: "Radio",
                        position: "right_bottom",
                        config: {
                                customCommand: "./modules/MMM-MplayerRadio/scripts/vlcWrapper.bas>
                                customCommandArgs: ["###URL###"],
                                showStations: false,
                                showLogos: false,
                                showTitles: true,
                                //showVolControls: false,
                                //autoplay: 0,
                                stations: [
                                        {
                                        //title: "OttoFM",
                                        url: "https://stream8.toserver.net:8443/ottofm.mp3",
                                        //logo: "https://upload.wikimedia.org/wikipedia/commons/a>
                                        }
                                ],
                                displayStationsOnStartup: false
                        },
                },

**Comment by Tom-Hirschberger** [comment] 2023-11-05 18:34
Hi, 
just released version 0.1.3 of the module which should fix the problem with the scripts.

Please run the following commands to update the module:

```bash
cd ~/MagicMirror/modules/MMM-MplayerRadio
git pull
npm install
```

And (if you use pm2 to start MagicMirror) restart MagicMirror with:

```bash
pm2 restart MagicMirror
```

**Comment by mfranchini** [comment] 2023-11-05 18:56
Thanks,
Tomorrow I perform a new version.
Good Night

Marco Franchini 29121 Piacenza Via Osimo, 21 Cell. +39 3487555030


Il giorno dom 5 nov 2023 alle 19:34 Thomas Hirschberger <
***@***.***> ha scritto:

**Comment by mfranchini** [comment] 2023-11-06 17:30
Hi,
Not work, when i press play button  the radio start, then if i press next o previous button then i press stop button, radio continue play and i don't know how stop it

**Comment by Tom-Hirschberger** [comment] 2023-11-06 19:36
Can you try to run the vlc Wrapper.bash script in a shell, kill the script by hitting CTRL+c and post the output here?

```bash
cd ~/MagicMirror
./modules/MMM-MplayerRadio/scripts/vlcWrapper.bash https://stream8.toserver.net:8443/ottofm.mp3
```

**Comment by mfranchini** [comment] 2023-11-06 19:42
I executer bash vlcWrapper.bash, and the answer is

Not enough arguments


Marco Franchini
3487555030

**Comment by Tom-Hirschberger** [comment] 2023-11-07 17:36
Are you sure you run:

```
cd ~/MagicMirror
./modules/MMM-MplayerRadio/scripts/vlcWrapper.bash https://stream8.toserver.net:8443/ottofm.mp3
```

The script expects the URL of the stream as first and only argument.

**Comment by mfranchini** [comment] 2023-11-07 17:39
Marco Franchini
3487555030

**Comment by mfranchini** [comment] 2023-11-07 17:40
Marco Franchini
3487555030

**Comment by Tom-Hirschberger** [comment] 2023-11-09 16:13
Sorry, but your last two messages had been empty.

Have you been able to run the command?

**Comment by mfranchini** [comment] 2023-11-09 16:16
Marco Franchini
3487555030

**Comment by Tom-Hirschberger** [comment] 2023-11-09 17:55
Sorry, but the message is still empty.
Maybe the E-Mail to Comment function of Github is broken.

**Comment by mfranchini** [comment] 2023-11-09 18:52
Sorry, try now


Marco Franchini
3487555030

**Comment by mfranchini** [comment] 2023-11-09 19:01
Hi,
I noticed that the images are blurry, I will try to make more as soon as I can

I’m sorry


Marco Franchini
3487555030

**Comment by mfranchini** [comment] 2023-11-09 19:46
Here







Marco Franchini
3487555030

**Comment by Tom-Hirschberger** [comment] 2023-11-10 19:18
Sorry, but your last message does not contain anything but the word "Here". I can not see any attachment neither in the browser nor in the GitHub App

**Comment by mfranchini** [comment] 2023-11-10 19:25
Hi,
i can try to transfer via WeTransfer now


Marco Franchini
3487555030

**Comment by mfranchini** [comment] 2023-11-10 19:27
***@***.*** sent you Log File

1 item, 28.4 KB in total ・ Expires on 17 November, 2023


Download link:
https://wetransfer.com/downloads/9b60949fd620b1d5713088fd249b9b7820231110192624/61f5645ba966816808b7e4acb8865ad220231110192646/6cd905?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid



Message:
Try now



1 item

Log.rtf - 28.4 KB


[Get more out of WeTransfer, get Pro](https://wetransfer.com/pro?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid)



About WeTransfer: https://wetransfer.com/about
Help: https://wetransfer.zendesk.com/hc/en-us
Legal: https://wetransfer.com/legal/terms


To make sure our emails arrive, please add ***@***.*** to [your contacts](https://wetransfer.zendesk.com/hc/en-us/articles/204909429).

**Comment by Tom-Hirschberger** [comment] 2023-11-10 19:31
I was able to download and view the file.
It looks like the radio stream stopped as it should in this case.

Currently i do not know why it works on the shell and in my setup but not in yours.

What version of node do you use?
What MagicMirror version do you use?

**Comment by mfranchini** [comment] 2023-11-10 19:35
Ok good
now i can not to see the both version, but tomorrow i check and send you the information required.

Good Luck

Marco Franchini
3487555030

**Comment by mfranchini** [comment] 2023-11-10 21:02
Ok i’m here

That are the version; 

***@***.***:~/MagicMirror $ cat package.json
{
	"name": "magicmirror",
	"version": "2.25.0”,


***@***.***:~ $ nodejs
Welcome to Node.js v12.22.12.


Marco Franchini
3487555030

**Comment by Tom-Hirschberger** [comment] 2023-11-10 21:05
OK.
You are running the current stable version of MagicMirror but you use a totally outdated node version.

For MagicMirror 2.25.0 Node needs to be at least version 20, the previous version of MagicMirror used version 16.

How did you update? Did you use the script of Sam?

**Comment by mfranchini** [comment] 2023-11-10 21:08
Who is Sam?

Marco Franchini
3487555030

**Comment by mfranchini** [comment] 2023-11-10 21:09
For installation i used this script

https://github.com/sdetweil/MagicMirror_scripts <https://github.com/sdetweil/MagicMirror_scripts>

Marco Franchini
3487555030

**Comment by Tom-Hirschberger** [comment] 2023-11-10 21:16
That's good. These are the scripts of sdetweil (Sam Detweil).
He updated his scripts in the last week as the had been problems on some systems.
Maybe you can do a update with force option.
As you already use 2.25.0 there should not be too much problems with the modules but the update script takes care to install the correct node version.

**Comment by mfranchini** [comment] 2023-11-10 21:19
Which command can i use for update node to last version?

Thanks

Marco Franchini
3487555030

**Comment by Tom-Hirschberger** [comment] 2023-11-10 21:24
You can either try to run

```bash
bash -c  "$(curl -sL https://raw.githubusercontent.com/sdetweil/MagicMirror_scripts/master/upgrade-script.sh)" force
```

Or you need to do the job manually. The instructions can be found here [https://deb.nodesource.com/](https://deb.nodesource.com/)

**Comment by mfranchini** [comment] 2023-11-10 21:24
This?

***@***.***:~ $ node -v
v20.8.0

Marco Franchini
3487555030

**Comment by Tom-Hirschberger** [comment] 2023-11-10 21:26
Yes. This version should be much better.

Does MMM-MplayerRadio work after you restarted?

**Comment by mfranchini** [comment] 2023-11-10 21:32
After update

***@***.***:~ $ nodejs -v
v12.22.12
***@***.***:~ $ node -v
v20.8.0

MMM-MplayerRadio work correctly, then is possible to close the issue, for me.

Thanks a lot

Good luck

Marco Franchini
3487555030

**Comment by Tom-Hirschberger** [comment] 2023-11-10 21:38
Great to hear that.
Have much fun with the module.

**Closed as completed** 2023-11-10 21:39 UTC
